WITH PD AS (SELECT 1 AS Month, *
FROM PD2023_WK04_JANUARY
UNION all
SELECT 2 AS Month, *
FROM PD2023_WK04_FEBRUARY
UNION all
SELECT 3 AS Month, *
FROM PD2023_WK04_MARCH
UNION all
SELECT 4 AS Month, *
FROM PD2023_WK04_APRIL
UNION all
SELECT 5 AS Month, *
FROM PD2023_WK04_MAY
UNION all
SELECT 6 AS Month, *
FROM PD2023_WK04_JUNE
UNION all
SELECT 7 AS Month, *
FROM PD2023_WK04_JULY
UNION all
SELECT 8 AS Month, *
FROM PD2023_WK04_AUGUST
UNION all
SELECT 9 AS Month, *
FROM PD2023_WK04_SEPTEMBER
UNION all
SELECT 10 AS Month, *
FROM PD2023_WK04_OCTOBER
UNION all
SELECT 11 AS Month, *
FROM PD2023_WK04_NOVEMBER
UNION all
SELECT 12 AS Month, *
FROM PD2023_WK04_DECEMBER)

SELECT
    PD.ID AS "ID",
    MIN(DATE_FROM_PARTS(2023, PD.MONTH, PD.JOINING_DAY)) AS "Joining Date",
    PD."'Account Type'" AS "Account Type",
    TO_DATE(PD."'Date of Birth'", 'MM/DD/YYYY') AS "Date of Birth",
    PD."'Ethnicity'" AS "Ethnicity"
FROM PD
    PIVOT (MAX(PD.VALUE) FOR PD.DEMOGRAPHIC IN ('Ethnicity', 'Account Type', 'Date of Birth'))
GROUP BY "ID", "Account Type", "Date of Birth", "Ethnicity"